env_id: PickCube-v1
num_envs: 16
obs:
  rgb: [base_camera]
  image_size: [64, 64]
encoder:
  backbone: resnet10
q_lr: 0.0001
capture_video: true
video_fps: 30
render_mode: rgb_array
eval_freq: 10000
total_timesteps: 1000000
